#!/usr/bin/env bash
# HotBox Pi Appliance — Hardware Watchdog & Log Rotation Setup
# Enables Pi 5 hardware watchdog for auto-recovery from system hangs.
# Configures journald log rotation to prevent SD card fill.
# Usage: sudo bash setup-watchdog.sh

set -euo pipefail

# ---------- Root check ----------
if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root (use sudo)." >&2
  exit 1
fi

# ---------- Load configuration ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/../config/hotbox.conf"

if [[ -f "$CONFIG_FILE" ]]; then
  echo "[watchdog] Loading $CONFIG_FILE"
  # shellcheck source=../config/hotbox.conf
  source "$CONFIG_FILE"
else
  echo "[watchdog] Warning: $CONFIG_FILE not found, using defaults"
fi

# ---------- Logging ----------
LOG_FILE="/var/log/hotbox-watchdog-setup.log"
exec > >(tee -a "$LOG_FILE") 2>&1
echo ""
echo "========================================"
echo " HotBox Watchdog Setup — $(date -Iseconds)"
echo "========================================"

# ---------- 1. Enable hardware watchdog in boot config ----------
echo ""
echo "[1/4] Enabling hardware watchdog in boot config..."

BOOT_CONFIG="/boot/firmware/config.txt"
if [[ ! -f "$BOOT_CONFIG" ]]; then
  # Fallback for older Pi OS layouts
  BOOT_CONFIG="/boot/config.txt"
fi

if [[ -f "$BOOT_CONFIG" ]]; then
  if grep -q "^dtparam=watchdog=on" "$BOOT_CONFIG" 2>/dev/null; then
    echo "[1/4] Watchdog already enabled in $BOOT_CONFIG."
  elif grep -q "^#.*dtparam=watchdog" "$BOOT_CONFIG" 2>/dev/null; then
    # Uncomment existing line
    sed -i 's/^#.*dtparam=watchdog.*/dtparam=watchdog=on/' "$BOOT_CONFIG"
    echo "[1/4] Uncommented and enabled watchdog in $BOOT_CONFIG."
  else
    echo "" >> "$BOOT_CONFIG"
    echo "# HotBox: Enable hardware watchdog for auto-recovery" >> "$BOOT_CONFIG"
    echo "dtparam=watchdog=on" >> "$BOOT_CONFIG"
    echo "[1/4] Added dtparam=watchdog=on to $BOOT_CONFIG."
  fi
else
  echo "[1/4] WARNING: Boot config not found at /boot/firmware/config.txt or /boot/config.txt"
  echo "[1/4] You may need to enable the watchdog manually."
fi

# ---------- 2. Install watchdog package ----------
echo ""
echo "[2/4] Installing watchdog package..."
if dpkg -l | grep -q "^ii  watchdog "; then
  echo "[2/4] watchdog package already installed."
else
  apt-get install -y watchdog
  echo "[2/4] watchdog package installed."
fi

# ---------- 3. Configure watchdog daemon ----------
echo ""
echo "[3/4] Configuring watchdog daemon..."

WATCHDOG_CONF="/etc/watchdog.conf"

# Back up existing config
if [[ -f "$WATCHDOG_CONF" ]]; then
  cp "$WATCHDOG_CONF" "${WATCHDOG_CONF}.hotbox-backup.$(date +%Y%m%d%H%M%S)"
fi

cat > "$WATCHDOG_CONF" <<'WATCHDOGCONF'
# HotBox Pi Appliance — Watchdog Configuration
# Auto-generated by setup-watchdog.sh
#
# If the system hangs (no watchdog pet for 15s), hardware resets the Pi.
# Also monitors system load and network connectivity.

watchdog-device = /dev/watchdog
watchdog-timeout = 15

# System load monitoring (24 = very high; prevents runaway processes)
max-load-1 = 24

# Network monitoring
interface = wlan0
ping = 127.0.0.1

# Check interval (seconds)
interval = 10
WATCHDOGCONF

echo "[3/4] Wrote $WATCHDOG_CONF (timeout=15s, interval=10s)."

# Enable and start watchdog service
systemctl enable watchdog.service 2>/dev/null || true
echo "[3/4] watchdog.service enabled."

# ---------- 4. Journald log rotation ----------
echo ""
echo "[4/4] Configuring journald log rotation..."

JOURNALD_CONF="/etc/systemd/journald.conf"

if [[ -f "$JOURNALD_CONF" ]]; then
  # Back up existing config
  cp "$JOURNALD_CONF" "${JOURNALD_CONF}.hotbox-backup.$(date +%Y%m%d%H%M%S)"

  # Set or update each parameter
  set_journald_param() {
    local param="$1"
    local value="$2"
    if grep -q "^${param}=" "$JOURNALD_CONF" 2>/dev/null; then
      sed -i "s/^${param}=.*/${param}=${value}/" "$JOURNALD_CONF"
    elif grep -q "^#${param}=" "$JOURNALD_CONF" 2>/dev/null; then
      sed -i "s/^#${param}=.*/${param}=${value}/" "$JOURNALD_CONF"
    else
      echo "${param}=${value}" >> "$JOURNALD_CONF"
    fi
  }

  set_journald_param "SystemMaxUse" "50M"
  set_journald_param "SystemMaxFileSize" "10M"
  set_journald_param "MaxRetentionSec" "7day"

  echo "[4/4] Journald configured: max 50M total, 10M per file, 7-day retention."
else
  echo "[4/4] WARNING: $JOURNALD_CONF not found. Creating minimal config."
  mkdir -p /etc/systemd
  cat > "$JOURNALD_CONF" <<'JOURNALDCONF'
[Journal]
SystemMaxUse=50M
SystemMaxFileSize=10M
MaxRetentionSec=7day
JOURNALDCONF
fi

# Restart journald to apply
systemctl restart systemd-journald 2>/dev/null || true
echo "[4/4] journald restarted with new limits."

# ---------- Done ----------
echo ""
echo "========================================"
echo " HotBox Watchdog Setup COMPLETE"
echo " Watchdog: 15s timeout, 10s interval"
echo " Journald: 50M max, 7-day retention"
echo " Log: $LOG_FILE"
echo "========================================"
echo ""
echo "NOTE: Reboot required for hardware watchdog to activate."
echo ""
